[package]
name = "pytera"
version = "0.1.0"
edition = "2018"

[lib]
name = "pytera"
crate-type = ["cdylib"]

[dependencies]
tera = "1.15.0"

[dependencies.pyo3]
version = "0.15.0"
features = ["extension-module"]
